### ISSUE TITLE
Question on IPFS forum

### ISSUE THREAD

**Issue by bmann** [fission-suite/get-ipfs#14]
See https://discuss.ipfs.io/t/detecting-from-a-website-if-ipfs-companion-and-ipfs-desktop-app-are-working/8165/5

> I was trying it out and noticed that it uses a check for window.ipfs to see if the extension is there. I then noticed that my IPFS companion (the chrome version) has window.ipfs disabled by default (https://docs.ipfs.io/how-to/companion-window-ipfs/).
>
>Because of this, I think the window.ipfs check will always fail even if the companion is installed in your browser. Right now, I am still looking into other ways of checking if a local node is running (hopefully automatically since I hope to not require users to turn on window.ipfs again for it to work if I can avoid it).

@dholms can you take a look and respond to the commenter when you get the chance.

**Comment by dholms** [comment]
Responded here: https://discuss.ipfs.io/t/detecting-from-a-website-if-ipfs-companion-and-ipfs-desktop-app-are-working/8165/7?u=dholms
